# Generated by Django 6.0.8 on 2026-09-30 01:38

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=150)),
                ('barcode', models.CharField(db_index=True, max_length=32, unique=True)),
                ('manufacturer', models.CharField(max_length=120)),
                ('unit', models.CharField(choices=[('dona', 'dona'), ('quti', 'quti'), ('ml', 'ml'), ('gr', 'gr')], max_length=10)),
                ('min_qoldiq', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('retsept_kerak', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('stir', models.CharField(blank=True, max_length=9)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(max_length=120)),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('pharmacist', 'Farmatsevt')], default='pharmacist', max_length=16)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('notify_enabled', models.BooleanField(default=True)),
                ('link_code', models.CharField(blank=True, max_length=12)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partiya_raqami', models.CharField(max_length=40)),
                ('yaroqlilik_sanasi', models.DateField(db_index=True)),
                ('kirim_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sotuv_narxi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('qabul_sanasi', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dori', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partiyalar', to='stock.medicine')),
                ('yetkazuvchi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stock.supplier')),
            ],
        ),
        migrations.CreateModel(
            name='ReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('turi', models.CharField(choices=[('muddat', 'muddat'), ('min_qoldiq', 'min_qoldiq')], max_length=16)),
                ('sana', models.DateField(db_index=True)),
                ('qolgan_kun', models.IntegerField()),
                ('qoldiq', models.DecimalField(decimal_places=2, max_digits=10)),
                ('chat_id', models.BigIntegerField()),
                ('holat', models.CharField(choices=[('yuborildi', 'yuborildi'), ('xato', 'xato')], max_length=10)),
                ('xato_matni', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eslatmalar', to='stock.batch')),
            ],
            options={
                'unique_together': {('partiya', 'turi', 'sana', 'chat_id')},
            },
        ),
        migrations.CreateModel(
            name='StockIn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sana', models.DateField()),
                ('hujjat_raqami', models.CharField(blank=True, max_length=40)),
                ('izoh', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='kirimlar', to='stock.batch')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('miqdor__gt', 0)), name='kirim_miqdor_pos')],
            },
        ),
        migrations.CreateModel(
            name='StockOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('miqdor', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('sabab', models.CharField(choices=[('sotuv', 'Sotuv'), ('qaytarish', 'Qaytarish'), ('yaroqsiz', 'Yaroqsiz')], max_length=12)),
                ('narx', models.DecimalField(decimal_places=2, max_digits=12)),
                ('sana', models.DateField()),
                ('izoh', models.TextField(blank=True)),
                ('manba', models.CharField(choices=[('api', 'api'), ('bot', 'bot')], default='api', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kim', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('partiya', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chiqimlar', to='stock.batch')),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('miqdor__gt', 0)), name='chiqim_miqdor_pos')],
            },
        ),
        migrations.AddConstraint(
            model_name='batch',
            constraint=models.CheckConstraint(condition=models.Q(('sotuv_narxi__gte', models.F('kirim_narxi'))), name='sotuv_gte_kirim'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('dori', 'partiya_raqami')},
        ),
    ]
